#!/usr/bin/env python
# A basic network scanner with hard coded IP addresses

import scapy.all as scapy

def scan (ip):
    arp_request = scapy.ARP(pdst=ip)
    print(arp_request.summary())
    
scan("172.16.5.1")
